"""Added comment_author

Revision ID: 0aaed6fc4387
Revises: d32fddec14d5
Create Date: 2021-03-27 20:38:45.175874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaed6fc4387'
down_revision = 'd32fddec14d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_table', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments_table', 'users_table', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments_table', type_='foreignkey')
    op.drop_column('comments_table', 'author_id')
    # ### end Alembic commands ###
