PROJECT_NAME = "MyProject"
SERVER_HOST = 'http://127.0.0.1:8000'

# Data Base
POSTGRES_SERVER = "localhost"
POSTGRES_USER = "adminuser"
POSTGRES_PASSWORD = "123"
POSTGRES_DB = "postgres"

# # Email
# SMTP_TLS = True
# SMTP_PORT = None
# SMTP_HOST = "SMTP_HOST"
# SMTP_USER = "SMTP_USER"
# SMTP_PASSWORD = "SMTP_PASSWORD"
# EMAILS_FROM_EMAIL = "EMAILS_FROM_EMAIL"
# EMAILS_FROM_NAME = "PROJECT_NAME"
# EMAIL_RESET_TOKEN_EXPIRE_HOURS = 48
# EMAIL_TEMPLATES_DIR = "/email-email-templates/build"
# EMAILS_ENABLED = SMTP_HOST and SMTP_PORT and EMAILS_FROM_EMAIL